# Generated by Django 3.0.7 on 2020-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_id', models.IntegerField(default=0, verbose_name='因子ID')),
                ('factor_name', models.CharField(max_length=100, verbose_name='因子名称')),
                ('factor_desc', models.CharField(default='', max_length=500, verbose_name='因子描述')),
            ],
            options={
                'verbose_name': '因子基本信息',
                'verbose_name_plural': '因子基本信息',
            },
        ),
    ]
