# Generated by Django 3.0.7 on 2020-06-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='factorinfo',
            table='factor_info',
        ),
    ]
