# Generated by Django 3.0.7 on 2020-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票简称')),
                ('stock_full_name', models.CharField(default='', max_length=100, verbose_name='股票全称')),
                ('listing_date', models.DateField(default='', verbose_name='上市日期')),
                ('registered_address', models.CharField(default='', max_length=200, verbose_name='注册地址')),
            ],
            options={
                'verbose_name': '股票基本信息',
                'verbose_name_plural': '股票基本信息',
            },
        ),
    ]
