# Generated by Django 3.0.7 on 2020-07-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200628_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinfo',
            options={'verbose_name': '股票', 'verbose_name_plural': '股票'},
        ),
    ]
