# Generated by Django 3.0.7 on 2020-06-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='optionalshares',
            table='optional_shares',
        ),
        migrations.AlterModelTable(
            name='stockcomments',
            table='stock_comments',
        ),
        migrations.AlterModelTable(
            name='userask',
            table='user_ask',
        ),
        migrations.AlterModelTable(
            name='userfavorite',
            table='user_favorite',
        ),
        migrations.AlterModelTable(
            name='usermessage',
            table='user_message',
        ),
    ]
