# Generated by Django 3.0.7 on 2020-07-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20200628_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockcomments',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
