# Generated by Django 3.0.7 on 2020-06-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200628_1347'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverifyrecord',
            table='users_email_verify_record',
        ),
    ]
